#!/usr/bin/env bash
# src/new.sh — schema wizard and new-resource generators
# Bash 3.2 compatible: no declare -A, no +=, no mapfile

# ---------------------------------------------------------------------------
# _seed_new_infer_sql_type <gen_name>
# Returns the SQL column type for a given generator name on stdout.
# ---------------------------------------------------------------------------
_seed_new_infer_sql_type() {
    local gen="$1"
    case "$gen" in
        uuid)                              printf 'VARCHAR(36)\n'  ;;
        number)                            printf 'INT\n'          ;;
        date)                              printf 'TIMESTAMP\n'    ;;
        bool)                              printf 'BOOLEAN\n'      ;;
        ip)                                printf 'VARCHAR(15)\n'  ;;
        url|email)                         printf 'VARCHAR(255)\n' ;;
        first_name|last_name|name|phone)   printf 'VARCHAR(100)\n' ;;
        lorem)                             printf 'TEXT\n'         ;;
        *)                                 printf 'VARCHAR(255)\n' ;;
    esac
}

# ---------------------------------------------------------------------------
# _seed_new_build_schema <table> <col1> <gen_spec1> [<col2> <gen_spec2> ...]
# Prints .seed file content to stdout. No I/O, no file writing.
# gen_spec may contain spaces (e.g. "number --min 1 --max 99") — pass each
# as a single quoted argument; the caller must pre-assemble each gen_spec.
# ---------------------------------------------------------------------------
_seed_new_build_schema() {
    local table="$1"; shift
    printf '# Generated by seed.sh new custom-schema\n'
    printf '# Usage: seed.sh custom --schema %s --count 10 --format sql\n' "$table"
    printf 'table=%s\n' "$table"
    while [[ $# -ge 2 ]]; do
        local col="$1" gen_spec="$2"; shift 2
        local gen_name="${gen_spec%% *}"
        local sql_type
        sql_type=$(_seed_new_infer_sql_type "$gen_name")
        printf '%s|%s|%s\n' "$col" "$sql_type" "$gen_spec"
    done
}

# ---------------------------------------------------------------------------
# seed_new <subcommand> [args...]
# Dispatcher for new-resource generators.
# ---------------------------------------------------------------------------
seed_new() {
    local sub="${1:-}"; shift || true
    case "$sub" in
        custom-schema) _seed_new_custom_schema "$@" ;;
        *)  printf 'Usage: seed.sh new <subcommand>\n' >&2
            printf 'Available: custom-schema\n' >&2
            return 1 ;;
    esac
}
