#!/usr/bin/env bash
SEED_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source "${PTYUNIT_HOME:-$SEED_HOME/../ptyunit}/assert.sh"
source "$SEED_HOME/tests/assert-ext.sh"
source "$SEED_HOME/seed.sh"

ptyunit_test_begin "_seed_new_infer_sql_type"

assert_eq "VARCHAR(36)"  "$(_seed_new_infer_sql_type uuid)"        "uuid → VARCHAR(36)"
assert_eq "INT"          "$(_seed_new_infer_sql_type number)"      "number → INT"
assert_eq "TIMESTAMP"    "$(_seed_new_infer_sql_type date)"        "date → TIMESTAMP"
assert_eq "BOOLEAN"      "$(_seed_new_infer_sql_type bool)"        "bool → BOOLEAN"
assert_eq "VARCHAR(15)"  "$(_seed_new_infer_sql_type ip)"          "ip → VARCHAR(15)"
assert_eq "VARCHAR(255)" "$(_seed_new_infer_sql_type url)"         "url → VARCHAR(255)"
assert_eq "VARCHAR(255)" "$(_seed_new_infer_sql_type email)"       "email → VARCHAR(255)"
assert_eq "VARCHAR(100)" "$(_seed_new_infer_sql_type first_name)"  "first_name → VARCHAR(100)"
assert_eq "VARCHAR(100)" "$(_seed_new_infer_sql_type last_name)"   "last_name → VARCHAR(100)"
assert_eq "VARCHAR(100)" "$(_seed_new_infer_sql_type name)"        "name → VARCHAR(100)"
assert_eq "VARCHAR(100)" "$(_seed_new_infer_sql_type phone)"       "phone → VARCHAR(100)"
assert_eq "TEXT"         "$(_seed_new_infer_sql_type lorem)"       "lorem → TEXT"
assert_eq "VARCHAR(255)" "$(_seed_new_infer_sql_type unknown_gen)" "unknown → VARCHAR(255) fallback"

ptyunit_test_begin "_seed_new_build_schema"

# Basic two-field output
out=$(_seed_new_build_schema users id uuid email email)
assert_contains "$out" 'table=users'              "_seed_new_build_schema: table= line"
assert_contains "$out" 'id|VARCHAR(36)|uuid'      "_seed_new_build_schema: uuid field line"
assert_contains "$out" 'email|VARCHAR(255)|email' "_seed_new_build_schema: email field line"

# Header and usage comments use actual table name
assert_contains "$out" '# Generated by seed.sh new custom-schema' \
    "_seed_new_build_schema: header comment"
assert_contains "$out" '# Usage: seed.sh custom --schema users' \
    "_seed_new_build_schema: usage comment with table name"

# gen_spec with flags passed as single quoted arg
out=$(_seed_new_build_schema orders qty "number --min 1 --max 99")
assert_contains "$out" 'qty|INT|number --min 1 --max 99' \
    "_seed_new_build_schema: flagged gen_spec preserved"

# date with --from only; --to absent when not passed
out=$(_seed_new_build_schema events ts "date --from 2020-01-01")
assert_contains "$out" 'ts|TIMESTAMP|date --from 2020-01-01' \
    "_seed_new_build_schema: date --from present"
[[ "$out" != *"--to"* ]]
assert_exit_code $? 0 "_seed_new_build_schema: --to absent when not in gen_spec"

# lorem with --sentences
out=$(_seed_new_build_schema posts body "lorem --sentences 2")
assert_contains "$out" 'body|TEXT|lorem --sentences 2' \
    "_seed_new_build_schema: lorem --sentences"

ptyunit_test_begin "seed_new dispatcher"

# No args → exits 1, stderr contains "Usage"
# Capture exit code BEFORE $? is clobbered by the next statement
out=$(seed_new 2>&1); ec=$?
assert_exit_code $ec 1 "seed_new: no args exits 1"
assert_contains "$out" 'Usage' "seed_new: no args prints Usage"

# Unknown subcommand → exits 1 (direct call: $? is reliable)
seed_new totally-unknown 2>/dev/null
assert_exit_code $? 1 "seed_new: unknown subcommand exits 1"

ptyunit_test_summary
